// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package controlschema

const FloatingIPTable = "FloatingIP"

type (
	FloatingIPFloatingStatus = string
	FloatingIPState          = string
)

var (
	FloatingIPFloatingStatusDown   FloatingIPFloatingStatus = "down"
	FloatingIPFloatingStatusActive FloatingIPFloatingStatus = "active"
	FloatingIPFloatingStatusError  FloatingIPFloatingStatus = "error"
	FloatingIPStatePending         FloatingIPState          = "pending"
	FloatingIPStateReady           FloatingIPState          = "ready"
	FloatingIPStateError           FloatingIPState          = "error"
	FloatingIPStateDeleting        FloatingIPState          = "deleting"
)

// FloatingIP defines an object in FloatingIP table
type FloatingIP struct {
	UUID            string                   `ovsdb:"_uuid"`
	Address         string                   `ovsdb:"address"`
	AppliedRevision int                      `ovsdb:"applied_revision"`
	CreatedAt       string                   `ovsdb:"created_at"`
	ExternalIDs     map[string]string        `ovsdb:"external_ids"`
	FixedIPAddress  string                   `ovsdb:"fixed_ip_address"`
	FloatingStatus  FloatingIPFloatingStatus `ovsdb:"floating_status"`
	ID              string                   `ovsdb:"id"`
	LastError       string                   `ovsdb:"last_error"`
	Port            *string                  `ovsdb:"port"`
	Project         string                   `ovsdb:"project"`
	ProviderNetwork string                   `ovsdb:"provider_network"`
	Revision        int                      `ovsdb:"revision"`
	Router          *string                  `ovsdb:"router"`
	State           FloatingIPState          `ovsdb:"state"`
	UpdatedAt       string                   `ovsdb:"updated_at"`
}
