// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package controlschema

const IPAllocationTable = "IPAllocation"

type (
	IPAllocationAllocationState = string
	IPAllocationState           = string
)

var (
	IPAllocationAllocationStateReserved  IPAllocationAllocationState = "reserved"
	IPAllocationAllocationStateAllocated IPAllocationAllocationState = "allocated"
	IPAllocationStatePending             IPAllocationState           = "pending"
	IPAllocationStateReady               IPAllocationState           = "ready"
	IPAllocationStateError               IPAllocationState           = "error"
	IPAllocationStateDeleting            IPAllocationState           = "deleting"
)

// IPAllocation defines an object in IPAllocation table
type IPAllocation struct {
	UUID            string                      `ovsdb:"_uuid"`
	Address         string                      `ovsdb:"address"`
	AllocationState IPAllocationAllocationState `ovsdb:"allocation_state"`
	AppliedRevision int                         `ovsdb:"applied_revision"`
	CreatedAt       string                      `ovsdb:"created_at"`
	ExternalIDs     map[string]string           `ovsdb:"external_ids"`
	ID              string                      `ovsdb:"id"`
	LastError       string                      `ovsdb:"last_error"`
	Port            *string                     `ovsdb:"port"`
	Project         string                      `ovsdb:"project"`
	Revision        int                         `ovsdb:"revision"`
	State           IPAllocationState           `ovsdb:"state"`
	Subnet          string                      `ovsdb:"subnet"`
	UpdatedAt       string                      `ovsdb:"updated_at"`
}
