// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package controlschema

import (
	"encoding/json"

	"github.com/ovn-org/libovsdb/model"
	"github.com/ovn-org/libovsdb/ovsdb"
)

// FullDatabaseModel returns the DatabaseModel object to be used in libovsdb
func FullDatabaseModel() (model.ClientDBModel, error) {
	return model.NewClientDBModel("PVN_Control", map[string]model.Model{
		"FloatingIP":        &FloatingIP{},
		"IPAllocation":      &IPAllocation{},
		"Network":           &Network{},
		"Node":              &Node{},
		"Operation":         &Operation{},
		"Port":              &Port{},
		"Project":           &Project{},
		"ProviderNetwork":   &ProviderNetwork{},
		"ProviderSegment":   &ProviderSegment{},
		"Router":            &Router{},
		"RouterInterface":   &RouterInterface{},
		"SecurityGroup":     &SecurityGroup{},
		"SecurityGroupRule": &SecurityGroupRule{},
		"Subnet":            &Subnet{},
	})
}

var schema = `{
  "name": "PVN_Control",
  "version": "1.0.0",
  "tables": {
    "FloatingIP": {
      "columns": {
        "address": {
          "type": "string"
        },
        "applied_revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0
            }
          }
        },
        "created_at": {
          "type": "string"
        },
        "external_ids": {
          "type": {
            "key": {
              "type": "string"
            },
            "value": {
              "type": "string"
            },
            "min": 0,
            "max": "unlimited"
          }
        },
        "fixed_ip_address": {
          "type": "string"
        },
        "floating_status": {
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "set",
                [
                  "down",
                  "active",
                  "error"
                ]
              ]
            }
          }
        },
        "id": {
          "type": "string"
        },
        "last_error": {
          "type": "string"
        },
        "port": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Port",
              "refType": "strong"
            },
            "min": 0,
            "max": 1
          }
        },
        "project": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Project",
              "refType": "strong"
            }
          }
        },
        "provider_network": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "ProviderNetwork",
              "refType": "strong"
            }
          }
        },
        "revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 1
            }
          }
        },
        "router": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Router",
              "refType": "strong"
            },
            "min": 0,
            "max": 1
          }
        },
        "state": {
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "set",
                [
                  "pending",
                  "ready",
                  "error",
                  "deleting"
                ]
              ]
            }
          }
        },
        "updated_at": {
          "type": "string"
        }
      },
      "indexes": [
        [
          "id"
        ],
        [
          "provider_network",
          "address"
        ]
      ],
      "isRoot": true
    },
    "IPAllocation": {
      "columns": {
        "address": {
          "type": "string"
        },
        "allocation_state": {
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "set",
                [
                  "reserved",
                  "allocated"
                ]
              ]
            }
          }
        },
        "applied_revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0
            }
          }
        },
        "created_at": {
          "type": "string"
        },
        "external_ids": {
          "type": {
            "key": {
              "type": "string"
            },
            "value": {
              "type": "string"
            },
            "min": 0,
            "max": "unlimited"
          }
        },
        "id": {
          "type": "string"
        },
        "last_error": {
          "type": "string"
        },
        "port": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Port",
              "refType": "strong"
            },
            "min": 0,
            "max": 1
          }
        },
        "project": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Project",
              "refType": "strong"
            }
          }
        },
        "revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 1
            }
          }
        },
        "state": {
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "set",
                [
                  "pending",
                  "ready",
                  "error",
                  "deleting"
                ]
              ]
            }
          }
        },
        "subnet": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Subnet",
              "refType": "strong"
            }
          }
        },
        "updated_at": {
          "type": "string"
        }
      },
      "indexes": [
        [
          "id"
        ],
        [
          "subnet",
          "address"
        ]
      ],
      "isRoot": true
    },
    "Network": {
      "columns": {
        "applied_revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0
            }
          }
        },
        "created_at": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "external": {
          "type": "boolean"
        },
        "external_ids": {
          "type": {
            "key": {
              "type": "string"
            },
            "value": {
              "type": "string"
            },
            "min": 0,
            "max": "unlimited"
          }
        },
        "id": {
          "type": "string"
        },
        "last_error": {
          "type": "string"
        },
        "mtu": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 576,
              "maxInteger": 9216
            }
          }
        },
        "name": {
          "type": "string"
        },
        "project": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Project",
              "refType": "strong"
            }
          }
        },
        "provider_network": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "ProviderNetwork",
              "refType": "strong"
            },
            "min": 0,
            "max": 1
          }
        },
        "revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 1
            }
          }
        },
        "state": {
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "set",
                [
                  "pending",
                  "ready",
                  "error",
                  "deleting"
                ]
              ]
            }
          }
        },
        "updated_at": {
          "type": "string"
        }
      },
      "indexes": [
        [
          "id"
        ],
        [
          "project",
          "name"
        ]
      ],
      "isRoot": true
    },
    "Node": {
      "columns": {
        "applied_revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0
            }
          }
        },
        "chassis_id": {
          "type": "string"
        },
        "created_at": {
          "type": "string"
        },
        "enabled": {
          "type": "boolean"
        },
        "external_ids": {
          "type": {
            "key": {
              "type": "string"
            },
            "value": {
              "type": "string"
            },
            "min": 0,
            "max": "unlimited"
          }
        },
        "id": {
          "type": "string"
        },
        "last_error": {
          "type": "string"
        },
        "last_seen_at": {
          "type": "string"
        },
        "management_address": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 1
            }
          }
        },
        "roles": {
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "set",
                [
                  "compute",
                  "gateway",
                  "central"
                ]
              ]
            },
            "min": 0,
            "max": 3
          }
        },
        "state": {
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "set",
                [
                  "pending",
                  "ready",
                  "error",
                  "deleting"
                ]
              ]
            }
          }
        },
        "updated_at": {
          "type": "string"
        }
      },
      "indexes": [
        [
          "id"
        ],
        [
          "name"
        ],
        [
          "chassis_id"
        ]
      ],
      "isRoot": true
    },
    "Operation": {
      "columns": {
        "action": {
          "type": "string"
        },
        "applied_revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0
            }
          }
        },
        "completed_at": {
          "type": "string"
        },
        "created_at": {
          "type": "string"
        },
        "error": {
          "type": "string"
        },
        "external_ids": {
          "type": {
            "key": {
              "type": "string"
            },
            "value": {
              "type": "string"
            },
            "min": 0,
            "max": "unlimited"
          }
        },
        "id": {
          "type": "string"
        },
        "idempotency_key": {
          "type": "string"
        },
        "last_error": {
          "type": "string"
        },
        "operation_status": {
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "set",
                [
                  "queued",
                  "running",
                  "succeeded",
                  "failed"
                ]
              ]
            }
          }
        },
        "revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 1
            }
          }
        },
        "started_at": {
          "type": "string"
        },
        "state": {
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "set",
                [
                  "pending",
                  "ready",
                  "error",
                  "deleting"
                ]
              ]
            }
          }
        },
        "target_id": {
          "type": "string"
        },
        "target_kind": {
          "type": "string"
        },
        "target_revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 1
            }
          }
        },
        "updated_at": {
          "type": "string"
        }
      },
      "indexes": [
        [
          "id"
        ],
        [
          "idempotency_key"
        ],
        [
          "target_kind",
          "target_id",
          "target_revision"
        ]
      ],
      "isRoot": true
    },
    "Port": {
      "columns": {
        "admin_state_up": {
          "type": "boolean"
        },
        "applied_revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0
            }
          }
        },
        "binding_status": {
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "set",
                [
                  "unbound",
                  "binding",
                  "bound",
                  "detaching",
                  "error"
                ]
              ]
            }
          }
        },
        "created_at": {
          "type": "string"
        },
        "external_ids": {
          "type": {
            "key": {
              "type": "string"
            },
            "value": {
              "type": "string"
            },
            "min": 0,
            "max": "unlimited"
          }
        },
        "fixed_ips": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Subnet",
              "refType": "strong"
            },
            "value": {
              "type": "string"
            },
            "min": 0,
            "max": "unlimited"
          }
        },
        "generation": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 1
            }
          }
        },
        "id": {
          "type": "string"
        },
        "last_error": {
          "type": "string"
        },
        "lsp_name": {
          "type": "string"
        },
        "mac_address": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "network": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Network",
              "refType": "strong"
            }
          }
        },
        "nic": {
          "type": "string"
        },
        "node": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Node",
              "refType": "weak"
            },
            "min": 0,
            "max": 1
          }
        },
        "project": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Project",
              "refType": "strong"
            }
          }
        },
        "requested_chassis": {
          "type": "string"
        },
        "revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 1
            }
          }
        },
        "security_groups": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "SecurityGroup",
              "refType": "strong"
            },
            "min": 0,
            "max": "unlimited"
          }
        },
        "state": {
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "set",
                [
                  "pending",
                  "ready",
                  "error",
                  "deleting"
                ]
              ]
            }
          }
        },
        "updated_at": {
          "type": "string"
        },
        "vmid": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0
            }
          }
        }
      },
      "indexes": [
        [
          "id"
        ],
        [
          "mac_address"
        ],
        [
          "lsp_name"
        ]
      ],
      "isRoot": true
    },
    "Project": {
      "columns": {
        "applied_revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0
            }
          }
        },
        "created_at": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "external_ids": {
          "type": {
            "key": {
              "type": "string"
            },
            "value": {
              "type": "string"
            },
            "min": 0,
            "max": "unlimited"
          }
        },
        "id": {
          "type": "string"
        },
        "last_error": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "pool_id": {
          "type": "string"
        },
        "revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 1
            }
          }
        },
        "state": {
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "set",
                [
                  "pending",
                  "ready",
                  "error",
                  "deleting"
                ]
              ]
            }
          }
        },
        "updated_at": {
          "type": "string"
        }
      },
      "indexes": [
        [
          "id"
        ],
        [
          "pool_id"
        ],
        [
          "name"
        ]
      ],
      "isRoot": true
    },
    "ProviderNetwork": {
      "columns": {
        "applied_revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0
            }
          }
        },
        "created_at": {
          "type": "string"
        },
        "default_segment": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "ProviderSegment",
              "refType": "weak"
            },
            "min": 0,
            "max": 1
          }
        },
        "description": {
          "type": "string"
        },
        "external_ids": {
          "type": {
            "key": {
              "type": "string"
            },
            "value": {
              "type": "string"
            },
            "min": 0,
            "max": "unlimited"
          }
        },
        "id": {
          "type": "string"
        },
        "last_error": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 1
            }
          }
        },
        "shared": {
          "type": "boolean"
        },
        "state": {
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "set",
                [
                  "pending",
                  "ready",
                  "error",
                  "deleting"
                ]
              ]
            }
          }
        },
        "updated_at": {
          "type": "string"
        }
      },
      "indexes": [
        [
          "id"
        ],
        [
          "name"
        ]
      ],
      "isRoot": true
    },
    "ProviderSegment": {
      "columns": {
        "applied_revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0
            }
          }
        },
        "created_at": {
          "type": "string"
        },
        "external_ids": {
          "type": {
            "key": {
              "type": "string"
            },
            "value": {
              "type": "string"
            },
            "min": 0,
            "max": "unlimited"
          }
        },
        "id": {
          "type": "string"
        },
        "last_error": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "network_type": {
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "set",
                [
                  "flat",
                  "vlan"
                ]
              ]
            }
          }
        },
        "physical_network": {
          "type": "string"
        },
        "provider_network": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "ProviderNetwork",
              "refType": "strong"
            }
          }
        },
        "revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 1
            }
          }
        },
        "state": {
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "set",
                [
                  "pending",
                  "ready",
                  "error",
                  "deleting"
                ]
              ]
            }
          }
        },
        "updated_at": {
          "type": "string"
        },
        "vlan_id": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0,
              "maxInteger": 4094
            }
          }
        }
      },
      "indexes": [
        [
          "id"
        ],
        [
          "provider_network",
          "name"
        ],
        [
          "physical_network",
          "network_type",
          "vlan_id"
        ]
      ],
      "isRoot": true
    },
    "Router": {
      "columns": {
        "applied_revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0
            }
          }
        },
        "created_at": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "enable_snat": {
          "type": "boolean"
        },
        "external_ids": {
          "type": {
            "key": {
              "type": "string"
            },
            "value": {
              "type": "string"
            },
            "min": 0,
            "max": "unlimited"
          }
        },
        "external_ip_address": {
          "type": "string"
        },
        "external_network": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Network",
              "refType": "strong"
            },
            "min": 0,
            "max": 1
          }
        },
        "external_subnet": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Subnet",
              "refType": "strong"
            },
            "min": 0,
            "max": 1
          }
        },
        "id": {
          "type": "string"
        },
        "last_error": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "project": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Project",
              "refType": "strong"
            }
          }
        },
        "revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 1
            }
          }
        },
        "state": {
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "set",
                [
                  "pending",
                  "ready",
                  "error",
                  "deleting"
                ]
              ]
            }
          }
        },
        "updated_at": {
          "type": "string"
        }
      },
      "indexes": [
        [
          "id"
        ],
        [
          "project",
          "name"
        ]
      ],
      "isRoot": true
    },
    "RouterInterface": {
      "columns": {
        "applied_revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0
            }
          }
        },
        "created_at": {
          "type": "string"
        },
        "external_ids": {
          "type": {
            "key": {
              "type": "string"
            },
            "value": {
              "type": "string"
            },
            "min": 0,
            "max": "unlimited"
          }
        },
        "id": {
          "type": "string"
        },
        "last_error": {
          "type": "string"
        },
        "port": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Port",
              "refType": "strong"
            },
            "min": 0,
            "max": 1
          }
        },
        "project": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Project",
              "refType": "strong"
            }
          }
        },
        "revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 1
            }
          }
        },
        "router": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Router",
              "refType": "strong"
            }
          }
        },
        "state": {
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "set",
                [
                  "pending",
                  "ready",
                  "error",
                  "deleting"
                ]
              ]
            }
          }
        },
        "subnet": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Subnet",
              "refType": "strong"
            }
          }
        },
        "updated_at": {
          "type": "string"
        }
      },
      "indexes": [
        [
          "id"
        ],
        [
          "router",
          "subnet"
        ]
      ],
      "isRoot": true
    },
    "SecurityGroup": {
      "columns": {
        "applied_revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0
            }
          }
        },
        "created_at": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "external_ids": {
          "type": {
            "key": {
              "type": "string"
            },
            "value": {
              "type": "string"
            },
            "min": 0,
            "max": "unlimited"
          }
        },
        "id": {
          "type": "string"
        },
        "last_error": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "project": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Project",
              "refType": "strong"
            }
          }
        },
        "revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 1
            }
          }
        },
        "state": {
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "set",
                [
                  "pending",
                  "ready",
                  "error",
                  "deleting"
                ]
              ]
            }
          }
        },
        "stateful": {
          "type": "boolean"
        },
        "updated_at": {
          "type": "string"
        }
      },
      "indexes": [
        [
          "id"
        ],
        [
          "project",
          "name"
        ]
      ],
      "isRoot": true
    },
    "SecurityGroupRule": {
      "columns": {
        "action": {
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "set",
                [
                  "allow",
                  "drop"
                ]
              ]
            }
          }
        },
        "applied_revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0
            }
          }
        },
        "created_at": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "direction": {
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "set",
                [
                  "ingress",
                  "egress"
                ]
              ]
            }
          }
        },
        "ethertype": {
          "type": {
            "key": {
              "type": "string",
              "enum": "IPv4"
            }
          }
        },
        "external_ids": {
          "type": {
            "key": {
              "type": "string"
            },
            "value": {
              "type": "string"
            },
            "min": 0,
            "max": "unlimited"
          }
        },
        "id": {
          "type": "string"
        },
        "last_error": {
          "type": "string"
        },
        "port_range_max": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0,
              "maxInteger": 65535
            }
          }
        },
        "port_range_min": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0,
              "maxInteger": 65535
            }
          }
        },
        "project": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Project",
              "refType": "strong"
            }
          }
        },
        "protocol": {
          "type": "string"
        },
        "remote_cidr": {
          "type": "string"
        },
        "remote_group": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "SecurityGroup",
              "refType": "strong"
            },
            "min": 0,
            "max": 1
          }
        },
        "revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 1
            }
          }
        },
        "security_group": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "SecurityGroup",
              "refType": "strong"
            }
          }
        },
        "state": {
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "set",
                [
                  "pending",
                  "ready",
                  "error",
                  "deleting"
                ]
              ]
            }
          }
        },
        "updated_at": {
          "type": "string"
        }
      },
      "indexes": [
        [
          "id"
        ]
      ],
      "isRoot": true
    },
    "Subnet": {
      "columns": {
        "allocation_pools": {
          "type": {
            "key": {
              "type": "string"
            },
            "min": 0,
            "max": "unlimited"
          }
        },
        "applied_revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 0
            }
          }
        },
        "cidr": {
          "type": "string"
        },
        "created_at": {
          "type": "string"
        },
        "dns_nameservers": {
          "type": {
            "key": {
              "type": "string"
            },
            "min": 0,
            "max": "unlimited"
          }
        },
        "enable_dhcp": {
          "type": "boolean"
        },
        "external_ids": {
          "type": {
            "key": {
              "type": "string"
            },
            "value": {
              "type": "string"
            },
            "min": 0,
            "max": "unlimited"
          }
        },
        "gateway_ip": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "last_error": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "network": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Network",
              "refType": "strong"
            }
          }
        },
        "project": {
          "type": {
            "key": {
              "type": "uuid",
              "refTable": "Project",
              "refType": "strong"
            }
          }
        },
        "revision": {
          "type": {
            "key": {
              "type": "integer",
              "minInteger": 1
            }
          }
        },
        "state": {
          "type": {
            "key": {
              "type": "string",
              "enum": [
                "set",
                [
                  "pending",
                  "ready",
                  "error",
                  "deleting"
                ]
              ]
            }
          }
        },
        "updated_at": {
          "type": "string"
        }
      },
      "indexes": [
        [
          "id"
        ],
        [
          "network",
          "name"
        ],
        [
          "network",
          "cidr"
        ]
      ],
      "isRoot": true
    }
  }
}`

func Schema() ovsdb.DatabaseSchema {
	var s ovsdb.DatabaseSchema
	err := json.Unmarshal([]byte(schema), &s)
	if err != nil {
		panic(err)
	}
	return s
}
