// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package controlschema

const NetworkTable = "Network"

type (
	NetworkState = string
)

var (
	NetworkStatePending  NetworkState = "pending"
	NetworkStateReady    NetworkState = "ready"
	NetworkStateError    NetworkState = "error"
	NetworkStateDeleting NetworkState = "deleting"
)

// Network defines an object in Network table
type Network struct {
	UUID            string            `ovsdb:"_uuid"`
	AppliedRevision int               `ovsdb:"applied_revision"`
	CreatedAt       string            `ovsdb:"created_at"`
	Description     string            `ovsdb:"description"`
	External        bool              `ovsdb:"external"`
	ExternalIDs     map[string]string `ovsdb:"external_ids"`
	ID              string            `ovsdb:"id"`
	LastError       string            `ovsdb:"last_error"`
	MTU             int               `ovsdb:"mtu"`
	Name            string            `ovsdb:"name"`
	ProviderNetwork *string           `ovsdb:"provider_network"`
	Revision        int               `ovsdb:"revision"`
	State           NetworkState      `ovsdb:"state"`
	UpdatedAt       string            `ovsdb:"updated_at"`
}
