// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package controlschema

const NodeTable = "Node"

type (
	NodeRoles = string
	NodeState = string
)

var (
	NodeRolesCompute  NodeRoles = "compute"
	NodeRolesGateway  NodeRoles = "gateway"
	NodeRolesCentral  NodeRoles = "central"
	NodeStatePending  NodeState = "pending"
	NodeStateReady    NodeState = "ready"
	NodeStateError    NodeState = "error"
	NodeStateDeleting NodeState = "deleting"
)

// Node defines an object in Node table
type Node struct {
	UUID              string            `ovsdb:"_uuid"`
	AppliedRevision   int               `ovsdb:"applied_revision"`
	ChassisID         string            `ovsdb:"chassis_id"`
	CreatedAt         string            `ovsdb:"created_at"`
	Enabled           bool              `ovsdb:"enabled"`
	ExternalIDs       map[string]string `ovsdb:"external_ids"`
	ID                string            `ovsdb:"id"`
	LastError         string            `ovsdb:"last_error"`
	LastSeenAt        string            `ovsdb:"last_seen_at"`
	ManagementAddress string            `ovsdb:"management_address"`
	Name              string            `ovsdb:"name"`
	Revision          int               `ovsdb:"revision"`
	Roles             []NodeRoles       `ovsdb:"roles"`
	State             NodeState         `ovsdb:"state"`
	UpdatedAt         string            `ovsdb:"updated_at"`
}
