// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package controlschema

const OperationTable = "Operation"

type (
	OperationOperationStatus = string
	OperationState           = string
)

var (
	OperationOperationStatusQueued    OperationOperationStatus = "queued"
	OperationOperationStatusRunning   OperationOperationStatus = "running"
	OperationOperationStatusSucceeded OperationOperationStatus = "succeeded"
	OperationOperationStatusFailed    OperationOperationStatus = "failed"
	OperationStatePending             OperationState           = "pending"
	OperationStateReady               OperationState           = "ready"
	OperationStateError               OperationState           = "error"
	OperationStateDeleting            OperationState           = "deleting"
)

// Operation defines an object in Operation table
type Operation struct {
	UUID            string                   `ovsdb:"_uuid"`
	Action          string                   `ovsdb:"action"`
	AppliedRevision int                      `ovsdb:"applied_revision"`
	CompletedAt     string                   `ovsdb:"completed_at"`
	CreatedAt       string                   `ovsdb:"created_at"`
	Error           string                   `ovsdb:"error"`
	ExternalIDs     map[string]string        `ovsdb:"external_ids"`
	ID              string                   `ovsdb:"id"`
	IdempotencyKey  string                   `ovsdb:"idempotency_key"`
	LastError       string                   `ovsdb:"last_error"`
	OperationStatus OperationOperationStatus `ovsdb:"operation_status"`
	Revision        int                      `ovsdb:"revision"`
	StartedAt       string                   `ovsdb:"started_at"`
	State           OperationState           `ovsdb:"state"`
	TargetID        string                   `ovsdb:"target_id"`
	TargetKind      string                   `ovsdb:"target_kind"`
	TargetRevision  int                      `ovsdb:"target_revision"`
	UpdatedAt       string                   `ovsdb:"updated_at"`
}
