// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package controlschema

const PortTable = "Port"

type (
	PortBindingStatus = string
	PortState         = string
)

var (
	PortBindingStatusUnbound   PortBindingStatus = "unbound"
	PortBindingStatusBinding   PortBindingStatus = "binding"
	PortBindingStatusBound     PortBindingStatus = "bound"
	PortBindingStatusDetaching PortBindingStatus = "detaching"
	PortBindingStatusError     PortBindingStatus = "error"
	PortStatePending           PortState         = "pending"
	PortStateReady             PortState         = "ready"
	PortStateError             PortState         = "error"
	PortStateDeleting          PortState         = "deleting"
)

// Port defines an object in Port table
type Port struct {
	UUID             string            `ovsdb:"_uuid"`
	AdminStateUp     bool              `ovsdb:"admin_state_up"`
	AppliedRevision  int               `ovsdb:"applied_revision"`
	BindingStatus    PortBindingStatus `ovsdb:"binding_status"`
	CreatedAt        string            `ovsdb:"created_at"`
	ExternalIDs      map[string]string `ovsdb:"external_ids"`
	FixedIPs         map[string]string `ovsdb:"fixed_ips"`
	Generation       int               `ovsdb:"generation"`
	ID               string            `ovsdb:"id"`
	LastError        string            `ovsdb:"last_error"`
	LspName          string            `ovsdb:"lsp_name"`
	MACAddress       string            `ovsdb:"mac_address"`
	Name             string            `ovsdb:"name"`
	Network          string            `ovsdb:"network"`
	Nic              string            `ovsdb:"nic"`
	Node             *string           `ovsdb:"node"`
	Project          string            `ovsdb:"project"`
	RequestedChassis string            `ovsdb:"requested_chassis"`
	Revision         int               `ovsdb:"revision"`
	SecurityGroups   []string          `ovsdb:"security_groups"`
	State            PortState         `ovsdb:"state"`
	UpdatedAt        string            `ovsdb:"updated_at"`
	Vmid             int               `ovsdb:"vmid"`
}
