// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package controlschema

const ProjectTable = "Project"

type (
	ProjectState = string
)

var (
	ProjectStatePending  ProjectState = "pending"
	ProjectStateReady    ProjectState = "ready"
	ProjectStateError    ProjectState = "error"
	ProjectStateDeleting ProjectState = "deleting"
)

// Project defines an object in Project table
type Project struct {
	UUID            string            `ovsdb:"_uuid"`
	AppliedRevision int               `ovsdb:"applied_revision"`
	CreatedAt       string            `ovsdb:"created_at"`
	Description     string            `ovsdb:"description"`
	ExternalIDs     map[string]string `ovsdb:"external_ids"`
	ID              string            `ovsdb:"id"`
	LastError       string            `ovsdb:"last_error"`
	Name            string            `ovsdb:"name"`
	PoolID          string            `ovsdb:"pool_id"`
	Revision        int               `ovsdb:"revision"`
	State           ProjectState      `ovsdb:"state"`
	UpdatedAt       string            `ovsdb:"updated_at"`
}
