// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package controlschema

const ProviderSegmentTable = "ProviderSegment"

type (
	ProviderSegmentNetworkType = string
	ProviderSegmentState       = string
)

var (
	ProviderSegmentNetworkTypeFlat ProviderSegmentNetworkType = "flat"
	ProviderSegmentNetworkTypeVLAN ProviderSegmentNetworkType = "vlan"
	ProviderSegmentStatePending    ProviderSegmentState       = "pending"
	ProviderSegmentStateReady      ProviderSegmentState       = "ready"
	ProviderSegmentStateError      ProviderSegmentState       = "error"
	ProviderSegmentStateDeleting   ProviderSegmentState       = "deleting"
)

// ProviderSegment defines an object in ProviderSegment table
type ProviderSegment struct {
	UUID            string                     `ovsdb:"_uuid"`
	AppliedRevision int                        `ovsdb:"applied_revision"`
	CreatedAt       string                     `ovsdb:"created_at"`
	ExternalIDs     map[string]string          `ovsdb:"external_ids"`
	ID              string                     `ovsdb:"id"`
	LastError       string                     `ovsdb:"last_error"`
	Name            string                     `ovsdb:"name"`
	NetworkType     ProviderSegmentNetworkType `ovsdb:"network_type"`
	PhysicalNetwork string                     `ovsdb:"physical_network"`
	ProviderNetwork string                     `ovsdb:"provider_network"`
	Revision        int                        `ovsdb:"revision"`
	State           ProviderSegmentState       `ovsdb:"state"`
	UpdatedAt       string                     `ovsdb:"updated_at"`
	VLANID          int                        `ovsdb:"vlan_id"`
}
