// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package controlschema

const ProviderNetworkTable = "ProviderNetwork"

type (
	ProviderNetworkState = string
)

var (
	ProviderNetworkStatePending  ProviderNetworkState = "pending"
	ProviderNetworkStateReady    ProviderNetworkState = "ready"
	ProviderNetworkStateError    ProviderNetworkState = "error"
	ProviderNetworkStateDeleting ProviderNetworkState = "deleting"
)

// ProviderNetwork defines an object in ProviderNetwork table
type ProviderNetwork struct {
	UUID            string               `ovsdb:"_uuid"`
	AppliedRevision int                  `ovsdb:"applied_revision"`
	CreatedAt       string               `ovsdb:"created_at"`
	DefaultSegment  *string              `ovsdb:"default_segment"`
	Description     string               `ovsdb:"description"`
	ExternalIDs     map[string]string    `ovsdb:"external_ids"`
	ID              string               `ovsdb:"id"`
	LastError       string               `ovsdb:"last_error"`
	Name            string               `ovsdb:"name"`
	Revision        int                  `ovsdb:"revision"`
	State           ProviderNetworkState `ovsdb:"state"`
	UpdatedAt       string               `ovsdb:"updated_at"`
}
