// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package controlschema

const RouterTable = "Router"

type (
	RouterState = string
)

var (
	RouterStatePending  RouterState = "pending"
	RouterStateReady    RouterState = "ready"
	RouterStateError    RouterState = "error"
	RouterStateDeleting RouterState = "deleting"
)

// Router defines an object in Router table
type Router struct {
	UUID              string            `ovsdb:"_uuid"`
	AppliedRevision   int               `ovsdb:"applied_revision"`
	CreatedAt         string            `ovsdb:"created_at"`
	Description       string            `ovsdb:"description"`
	EnableSNAT        bool              `ovsdb:"enable_snat"`
	ExternalIDs       map[string]string `ovsdb:"external_ids"`
	ExternalIPAddress string            `ovsdb:"external_ip_address"`
	ExternalNetwork   *string           `ovsdb:"external_network"`
	ExternalSubnet    *string           `ovsdb:"external_subnet"`
	ID                string            `ovsdb:"id"`
	LastError         string            `ovsdb:"last_error"`
	Name              string            `ovsdb:"name"`
	Revision          int               `ovsdb:"revision"`
	State             RouterState       `ovsdb:"state"`
	UpdatedAt         string            `ovsdb:"updated_at"`
}
