// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package controlschema

const RouterInterfaceTable = "RouterInterface"

type (
	RouterInterfaceState = string
)

var (
	RouterInterfaceStatePending  RouterInterfaceState = "pending"
	RouterInterfaceStateReady    RouterInterfaceState = "ready"
	RouterInterfaceStateError    RouterInterfaceState = "error"
	RouterInterfaceStateDeleting RouterInterfaceState = "deleting"
)

// RouterInterface defines an object in RouterInterface table
type RouterInterface struct {
	UUID            string               `ovsdb:"_uuid"`
	AppliedRevision int                  `ovsdb:"applied_revision"`
	CreatedAt       string               `ovsdb:"created_at"`
	ExternalIDs     map[string]string    `ovsdb:"external_ids"`
	ID              string               `ovsdb:"id"`
	LastError       string               `ovsdb:"last_error"`
	Port            *string              `ovsdb:"port"`
	Revision        int                  `ovsdb:"revision"`
	Router          string               `ovsdb:"router"`
	State           RouterInterfaceState `ovsdb:"state"`
	Subnet          string               `ovsdb:"subnet"`
	UpdatedAt       string               `ovsdb:"updated_at"`
}
