// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package controlschema

const SecurityGroupRuleTable = "SecurityGroupRule"

type (
	SecurityGroupRuleAction    = string
	SecurityGroupRuleDirection = string
	SecurityGroupRuleEthertype = string
	SecurityGroupRuleState     = string
)

var (
	SecurityGroupRuleActionAllow      SecurityGroupRuleAction    = "allow"
	SecurityGroupRuleActionDrop       SecurityGroupRuleAction    = "drop"
	SecurityGroupRuleDirectionIngress SecurityGroupRuleDirection = "ingress"
	SecurityGroupRuleDirectionEgress  SecurityGroupRuleDirection = "egress"
	SecurityGroupRuleEthertypeIpv4    SecurityGroupRuleEthertype = "IPv4"
	SecurityGroupRuleStatePending     SecurityGroupRuleState     = "pending"
	SecurityGroupRuleStateReady       SecurityGroupRuleState     = "ready"
	SecurityGroupRuleStateError       SecurityGroupRuleState     = "error"
	SecurityGroupRuleStateDeleting    SecurityGroupRuleState     = "deleting"
)

// SecurityGroupRule defines an object in SecurityGroupRule table
type SecurityGroupRule struct {
	UUID            string                     `ovsdb:"_uuid"`
	Action          SecurityGroupRuleAction    `ovsdb:"action"`
	AppliedRevision int                        `ovsdb:"applied_revision"`
	CreatedAt       string                     `ovsdb:"created_at"`
	Description     string                     `ovsdb:"description"`
	Direction       SecurityGroupRuleDirection `ovsdb:"direction"`
	Ethertype       SecurityGroupRuleEthertype `ovsdb:"ethertype"`
	ExternalIDs     map[string]string          `ovsdb:"external_ids"`
	ID              string                     `ovsdb:"id"`
	LastError       string                     `ovsdb:"last_error"`
	PortRangeMax    int                        `ovsdb:"port_range_max"`
	PortRangeMin    int                        `ovsdb:"port_range_min"`
	Project         string                     `ovsdb:"project"`
	Protocol        string                     `ovsdb:"protocol"`
	RemoteCidr      string                     `ovsdb:"remote_cidr"`
	RemoteGroup     *string                    `ovsdb:"remote_group"`
	Revision        int                        `ovsdb:"revision"`
	SecurityGroup   string                     `ovsdb:"security_group"`
	State           SecurityGroupRuleState     `ovsdb:"state"`
	UpdatedAt       string                     `ovsdb:"updated_at"`
}
