// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package controlschema

const SecurityGroupTable = "SecurityGroup"

type (
	SecurityGroupState = string
)

var (
	SecurityGroupStatePending  SecurityGroupState = "pending"
	SecurityGroupStateReady    SecurityGroupState = "ready"
	SecurityGroupStateError    SecurityGroupState = "error"
	SecurityGroupStateDeleting SecurityGroupState = "deleting"
)

// SecurityGroup defines an object in SecurityGroup table
type SecurityGroup struct {
	UUID            string             `ovsdb:"_uuid"`
	AppliedRevision int                `ovsdb:"applied_revision"`
	CreatedAt       string             `ovsdb:"created_at"`
	Description     string             `ovsdb:"description"`
	ExternalIDs     map[string]string  `ovsdb:"external_ids"`
	ID              string             `ovsdb:"id"`
	LastError       string             `ovsdb:"last_error"`
	Name            string             `ovsdb:"name"`
	Project         string             `ovsdb:"project"`
	Revision        int                `ovsdb:"revision"`
	State           SecurityGroupState `ovsdb:"state"`
	Stateful        bool               `ovsdb:"stateful"`
	UpdatedAt       string             `ovsdb:"updated_at"`
}
