// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package controlschema

const SubnetTable = "Subnet"

type (
	SubnetState = string
)

var (
	SubnetStatePending  SubnetState = "pending"
	SubnetStateReady    SubnetState = "ready"
	SubnetStateError    SubnetState = "error"
	SubnetStateDeleting SubnetState = "deleting"
)

// Subnet defines an object in Subnet table
type Subnet struct {
	UUID            string            `ovsdb:"_uuid"`
	AllocationPools []string          `ovsdb:"allocation_pools"`
	AppliedRevision int               `ovsdb:"applied_revision"`
	Cidr            string            `ovsdb:"cidr"`
	CreatedAt       string            `ovsdb:"created_at"`
	DNSNameservers  []string          `ovsdb:"dns_nameservers"`
	EnableDhcp      bool              `ovsdb:"enable_dhcp"`
	ExternalIDs     map[string]string `ovsdb:"external_ids"`
	GatewayIP       string            `ovsdb:"gateway_ip"`
	ID              string            `ovsdb:"id"`
	LastError       string            `ovsdb:"last_error"`
	Name            string            `ovsdb:"name"`
	Network         string            `ovsdb:"network"`
	Revision        int               `ovsdb:"revision"`
	State           SubnetState       `ovsdb:"state"`
	UpdatedAt       string            `ovsdb:"updated_at"`
}
